// Generated by gencpp from file rt_exam/rotate.msg
// DO NOT EDIT!


#ifndef RT_EXAM_MESSAGE_ROTATE_H
#define RT_EXAM_MESSAGE_ROTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rt_exam
{
template <class ContainerAllocator>
struct rotate_
{
  typedef rotate_<ContainerAllocator> Type;

  rotate_()
    : speed(0)  {
    }
  rotate_(const ContainerAllocator& _alloc)
    : speed(0)  {
  (void)_alloc;
    }



   typedef int64_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::rt_exam::rotate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rt_exam::rotate_<ContainerAllocator> const> ConstPtr;

}; // struct rotate_

typedef ::rt_exam::rotate_<std::allocator<void> > rotate;

typedef boost::shared_ptr< ::rt_exam::rotate > rotatePtr;
typedef boost::shared_ptr< ::rt_exam::rotate const> rotateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rt_exam::rotate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rt_exam::rotate_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rt_exam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rt_exam': ['/home/acer/houman-rtech/src/rt_exam/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rt_exam::rotate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rt_exam::rotate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_exam::rotate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rt_exam::rotate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_exam::rotate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rt_exam::rotate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rt_exam::rotate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4734ede392d478601ffe9898680ff4b5";
  }

  static const char* value(const ::rt_exam::rotate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4734ede392d47860ULL;
  static const uint64_t static_value2 = 0x1ffe9898680ff4b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rt_exam::rotate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rt_exam/rotate";
  }

  static const char* value(const ::rt_exam::rotate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rt_exam::rotate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 speed\n\
";
  }

  static const char* value(const ::rt_exam::rotate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rt_exam::rotate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rotate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rt_exam::rotate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rt_exam::rotate_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<int64_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RT_EXAM_MESSAGE_ROTATE_H
